import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@/services/clerk/componentes/ClerkProvider";
import { ThemeProvider } from "next-themes";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${outfitSans.variable} antialiased font-sans`}
          suppressHydrationWarning>
          <ThemeProvider attribute="class" defaultTheme="system"
          enableColorScheme
          disableTransitionOnChange
          >
            {children}
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
